### ISSUE TITLE
Incorrect git clone URL for app in README

### ISSUE THREAD

**Issue by secondstreetmedia** [gauravtiwari/webpacker-example-app#2]
In the section titled "Running in development" the git clone URL appears as:
`git clone git@github.com:gauravtiwari/example-webpacker-app.git`
but it should be:
`git clone git@github.com:gauravtiwari/webpacker-example-app.git`

**Comment by gauravtiwari** [comment]
Fixed @secondstreetmedia. Thank you 👍

**Comment by secondstreetmedia** [comment]
Sorry, just noticed the next line need correcting as well:
`cd example-webpacker-app`
should be:
`cd webpacker-example-app`

**Comment by gauravtiwari** [comment]
Fixed 🎉  Sorry, didn't notice it either. Thanks for pointing out 👍
